language: ruby
services:
  - postgresql
cache:
  - bundler
before_install:
  - nvm install --lts
  - gem install bundler
before_script:
  - bundle install --jobs=3 --retry=3
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake assets:precompile
script:
  - bundle exec rspec